language: ruby
script:
  - 'rake lint'
  - 'rake spec'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
env:
  - PUPPET_VERSION=2.7.26
  - PUPPET_VERSION=3.8.7
  - PUPPET_VERSION=4.4.2
matrix:
  allow_failures:
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.26
gemfile: .travis/Gemfile

